import gradio as gr
from gradio_seq_diff import seq_diff
import matplotlib.pyplot as plt

def generate_msaplot():
    seq1 = "CAGGTGCACCTGCAGGAGTCGGGCCCCGGACTAGTGAAGTCTTCGGAGACCCTGTCCCTCACCTGCACTGTCTCTGGTGACTCCATCAGACGTGATACTTACTACTGGAGCTGGATCCGGCAGACTCCGGGGAAGGGACTGGAGTGGCTTGGATATGTCTTTAAAAGTGGGAGCACAAAGTACAACCCCTCCTTCAAGCGTCGAGTCGACATATCAGTAGACACGTCCAAGGAGCAGTTCTCCCTGACATTGACGTCTGTGACCACTGCGGACACGGCCGTATACTTCTGTGCGAGAGAGTGGTACTATGGTTCGGGGGCCCCCCACAACTGGCTCGACTCCTGGAGCCAGGGAACCCTGGTCACCGTCTCCTCAG"
    seq2 = "CAGGTGCACCTGCAGGAGTCGGGCCCCGGACTAGTGAAGTCTTCGGAGACCCTGTCCCTCACCTGCACTGTCTCTGGTGACTCCATCAGACGTGATACTTACTACTGGAGCTGGATCCGGCAGACTCCGGGGAAGGGACTGGAGTGGCTTGGATATGTCTTTAAAAGTGGGAGCACAAAGTACAACCCCTCCTTCAAGCGTCGAGTCGACATATCAGTAGACACGTCCAAGGAGCAGTTCTCCCTGACATTGACGTCTGTGACCACTGCGGACACGGCCGTATACTTCTGTGCGAGAGAGTGGTACTATGGTTCGGGGGCCCCCCACAACTGGCTCGACTCCTGGAGCCAGGGAACCCTGGTCACCGTCTCCTCAG"
    germline = "CAGGTGCAGCTGCAGGAGTCGGGCCCAGGACTGGTGAAGCCTTCGGAGACCCTGTCCCTCACCTGCACTGTCTCTGGTGGCTCCATCAG------TAGTTACTACTGGAGCTGGATCCGGCAGCCCCCAGGGAAGGGACTGGAGTGGATTGGGTATATCTATTACAGTGGGAGCACCAACTACAACCCCTCCCTCAAGAGTCGAGTCACCATATCAGTAGACACGTCCAAGAACCAGTTCTCCCTGAAGCTGAGCTCTGTGACCGCTGCGGACACGGCCGTGTATTACTGTGCGAGAGAGTGGTACTATGGTTCGGGGGCCCCCCACAACTGGTTCGACTCCTGGGGCCAAGGAACCCTGGTCACCGTCTCCTCAG"

    fig, axes = plt.subplots(figsize=(12, 24))
    from msaplot import DrawComplexMSA, GetColorMap, DrawAnnotation, DrawSeqLogo, DrawMSA, DrawConsensusHisto

    DrawComplexMSA(
        msa=[seq1, seq2, germline],
        wrap=50,
        seq_names=['seq1', 'seq2', 'germline'],
        color_map=GetColorMap("dna"),
        panels=[DrawAnnotation, DrawSeqLogo, DrawMSA, DrawConsensusHisto],
        panel_params=[
            {"annotations": [["CDR1", 75, 104], ["CDR2", 156, 176], ["CDR3", 288, 344]]},
            {},
            {"show_char": True},
            {}
        ],
        figsize=[12, 24]
    )
    plt.close(fig)
    return fig

demo = gr.Interface(
    fn=generate_msaplot,
    inputs=None,
    outputs=seq_diff(
        msa=[
            "CAGGTGCACCTGCAGGAGTCGGGCCCCGGACTAGTGAAGTCTTCGGAGACCCTGTCCCTCACCTGCACTGTCTCTGGTGACTCCATCAGACGTGATACTTACTACTGGAGCTGGATCCGGCAGACTCCGGGGAAGGGACTGGAGTGGCTTGGATATGTCTTTAAAAGTGGGAGCACAAAGTACAACCCCTCCTTCAAGCGTCGAGTCGACATATCAGTAGACACGTCCAAGGAGCAGTTCTCCCTGACATTGACGTCTGTGACCACTGCGGACACGGCCGTATACTTCTGTGCGAGAGAGTGGTACTATGGTTCGGGGGCCCCCCACAACTGGCTCGACTCCTGGAGCCAGGGAACCCTGGTCACCGTCTCCTCAG",
            "CAGGTGCACCTGCAGGAGTCGGGCCCCGGACTAGTGAAGTCTTCGGAGACCCTGTCCCTCACCTGCACTGTCTCTGGTGACTCCATCAGACGTGATACTTACTACTGGAGCTGGATCCGGCAGACTCCGGGGAAGGGACTGGAGTGGCTTGGATATGTCTTTAAAAGTGGGAGCACAAAGTACAACCCCTCCTTCAAGCGTCGAGTCGACATATCAGTAGACACGTCCAAGGAGCAGTTCTCCCTGACATTGACGTCTGTGACCACTGCGGACACGGCCGTATACTTCTGTGCGAGAGAGTGGTACTATGGTTCGGGGGCCCCCCACAACTGGCTCGACTCCTGGAGCCAGGGAACCCTGGTCACCGTCTCCTCAG",
            "CAGGTGCAGCTGCAGGAGTCGGGCCCAGGACTGGTGAAGCCTTCGGAGACCCTGTCCCTCACCTGCACTGTCTCTGGTGGCTCCATCAG------TAGTTACTACTGGAGCTGGATCCGGCAGCCCCCAGGGAAGGGACTGGAGTGGATTGGGTATATCTATTACAGTGGGAGCACCAACTACAACCCCTCCCTCAAGAGTCGAGTCACCATATCAGTAGACACGTCCAAGAACCAGTTCTCCCTGAAGCTGAGCTCTGTGACCGCTGCGGACACGGCCGTGTATTACTGTGCGAGAGAGTGGTACTATGGTTCGGGGGCCCCCCACAACTGGTTCGACTCCTGGGGCCAAGGAACCCTGGTCACCGTCTCCTCAG"
        ],
        seq_names=['seq1', 'seq2', 'germline'],
        wrap=50,
        color_map=GetColorMap("dna"),
        panels=[DrawAnnotation, DrawSeqLogo, DrawMSA, DrawConsensusHisto],
        panel_params=[
            {"annotations": [["CDR1", 75, 104], ["CDR2", 156, 176], ["CDR3", 288, 344]]},
            {},
            {"show_char": True},
            {}
        ],
        width=800,
        height=1600
    ),
    title="Tonic's MSAPlot Demo",
    description="Displaying a Multiple Sequence Alignment plot using the seq_diff component."
)

if __name__ == "__main__":
    demo.launch()
